### ISSUE TITLE
JSON接口获取插件列表以及下载地址

### ISSUE THREAD

**Issue by elseif** [FoxCD/WoWTool#1]
怀旧服
`https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=1&gameVersionFlavor=wow_classic`
正式服
`https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=1&gameVersionFlavor=wow_retail`

**Comment by FoxCD** [comment]
感谢提供这个地址，新版已经使用

**Comment by FoxCD** [comment]
已经合并至master
